--------------------------------------------------------
--  File created - Monday-May-25-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CLAIMS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BALANG"."CLAIMS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FAILED_JOBS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BALANG"."FAILED_JOBS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MIGRATIONS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BALANG"."MIGRATIONS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PERSONAL_ACCESS_TOKENS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BALANG"."PERSONAL_ACCESS_TOKENS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence REPORTS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BALANG"."REPORTS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USERS_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BALANG"."USERS_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CLAIMS
--------------------------------------------------------

  CREATE TABLE "BALANG"."CLAIMS" 
   (	"ID" NUMBER(19,0), 
	"REPORT_ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0), 
	"PESAN_VALIDASI" CLOB, 
	"STATUS" VARCHAR2(255 BYTE) DEFAULT 'pending', 
	"CATATAN_ADMIN" CLOB, 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("PESAN_VALIDASI") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("CATATAN_ADMIN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table FAILED_JOBS
--------------------------------------------------------

  CREATE TABLE "BALANG"."FAILED_JOBS" 
   (	"ID" NUMBER(19,0), 
	"UUID" VARCHAR2(255 BYTE), 
	"CONNECTION" CLOB, 
	"QUEUE" CLOB, 
	"PAYLOAD" CLOB, 
	"EXCEPTION" CLOB, 
	"FAILED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONNECTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("QUEUE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("EXCEPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table MIGRATIONS
--------------------------------------------------------

  CREATE TABLE "BALANG"."MIGRATIONS" 
   (	"ID" NUMBER(10,0), 
	"MIGRATION" VARCHAR2(255 BYTE), 
	"BATCH" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PASSWORD_RESET_TOKENS
--------------------------------------------------------

  CREATE TABLE "BALANG"."PASSWORD_RESET_TOKENS" 
   (	"EMAIL" VARCHAR2(255 BYTE), 
	"TOKEN" VARCHAR2(255 BYTE), 
	"CREATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSONAL_ACCESS_TOKENS
--------------------------------------------------------

  CREATE TABLE "BALANG"."PERSONAL_ACCESS_TOKENS" 
   (	"ID" NUMBER(19,0), 
	"TOKENABLE_TYPE" VARCHAR2(255 BYTE), 
	"TOKENABLE_ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"TOKEN" VARCHAR2(64 BYTE), 
	"ABILITIES" CLOB, 
	"LAST_USED_AT" TIMESTAMP (6), 
	"EXPIRES_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ABILITIES") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "BALANG"."REPORTS" 
   (	"ID" NUMBER(19,0), 
	"USER_ID" NUMBER(19,0), 
	"FOTO_LAPORAN" VARCHAR2(255 BYTE), 
	"NAMA_LAPORAN" VARCHAR2(255 BYTE), 
	"JENIS_LAPORAN" VARCHAR2(255 BYTE), 
	"LOKASI_LAPORAN" VARCHAR2(255 BYTE), 
	"DESKRIPSI_LAPORAN" VARCHAR2(255 BYTE), 
	"TANGGAL_LAPORAN" DATE, 
	"WAKTU_LAPORAN" DATE, 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"STATUS" VARCHAR2(255 BYTE) DEFAULT 'aktif'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "BALANG"."USERS" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"ROLE" VARCHAR2(255 BYTE), 
	"EMAIL_VERIFIED_AT" TIMESTAMP (6), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"REMEMBER_TOKEN" VARCHAR2(100 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BALANG.CLAIMS
SET DEFINE OFF;
REM INSERTING into BALANG.FAILED_JOBS
SET DEFINE OFF;
REM INSERTING into BALANG.MIGRATIONS
SET DEFINE OFF;
Insert into BALANG.MIGRATIONS (ID,MIGRATION,BATCH) values ('1','2014_10_12_000000_create_users_table','1');
Insert into BALANG.MIGRATIONS (ID,MIGRATION,BATCH) values ('2','2014_10_12_100000_create_password_reset_tokens_table','1');
Insert into BALANG.MIGRATIONS (ID,MIGRATION,BATCH) values ('3','2019_08_19_000000_create_failed_jobs_table','1');
Insert into BALANG.MIGRATIONS (ID,MIGRATION,BATCH) values ('4','2019_12_14_000001_create_personal_access_tokens_table','1');
Insert into BALANG.MIGRATIONS (ID,MIGRATION,BATCH) values ('5','2026_05_05_041352_create_reports_table','1');
Insert into BALANG.MIGRATIONS (ID,MIGRATION,BATCH) values ('6','2026_05_07_033755_add_status_to_reports_table','1');
Insert into BALANG.MIGRATIONS (ID,MIGRATION,BATCH) values ('7','2026_05_07_044714_create_claims_table','1');
REM INSERTING into BALANG.PASSWORD_RESET_TOKENS
SET DEFINE OFF;
REM INSERTING into BALANG.PERSONAL_ACCESS_TOKENS
SET DEFINE OFF;
REM INSERTING into BALANG.REPORTS
SET DEFINE OFF;
Insert into BALANG.REPORTS (ID,USER_ID,FOTO_LAPORAN,NAMA_LAPORAN,JENIS_LAPORAN,LOKASI_LAPORAN,DESKRIPSI_LAPORAN,TANGGAL_LAPORAN,WAKTU_LAPORAN,CREATED_AT,UPDATED_AT,STATUS) values ('1',null,'default.jpg','Laporan Kerusakan Jalan','kehilangan','Jakarta Pusat','Terdapat lubang besar di tengah jalan utama.',to_date('25-05-2026','DD-MM-RRRR'),to_date('25-05-2026','DD-MM-RRRR'),to_timestamp('25-05-2026 10.06.29,000000000','DD-MM-RRRR HH24.MI.SSXFF'),to_timestamp('25-05-2026 10.06.29,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'aktif');
REM INSERTING into BALANG.USERS
SET DEFINE OFF;
Insert into BALANG.USERS (ID,NAME,EMAIL,ROLE,EMAIL_VERIFIED_AT,PASSWORD,REMEMBER_TOKEN,CREATED_AT,UPDATED_AT) values ('1','Test User','test@example.com','user',to_timestamp('25-05-2026 10.06.29,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'$2y$10$mKOscbdjN5qgHk6XsOAf7OVqu8uvrG.heUBYF8ds/sDIt3OlvdXMy','Vh687t5JR0',to_timestamp('25-05-2026 10.06.29,000000000','DD-MM-RRRR HH24.MI.SSXFF'),to_timestamp('25-05-2026 10.06.29,000000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into BALANG.USERS (ID,NAME,EMAIL,ROLE,EMAIL_VERIFIED_AT,PASSWORD,REMEMBER_TOKEN,CREATED_AT,UPDATED_AT) values ('2','Admin User','admin@example.com','admin',to_timestamp('25-05-2026 10.06.29,000000000','DD-MM-RRRR HH24.MI.SSXFF'),'$2y$10$W28bMwjl/zEJohh0anvD4u6rJau10MDptsbovGXN.waCq3A5sCJy6','zkKCKLH2t9',to_timestamp('25-05-2026 10.06.29,000000000','DD-MM-RRRR HH24.MI.SSXFF'),to_timestamp('25-05-2026 10.06.29,000000000','DD-MM-RRRR HH24.MI.SSXFF'));
--------------------------------------------------------
--  DDL for Index FAILED_JOBS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."FAILED_JOBS_ID_PK" ON "BALANG"."FAILED_JOBS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PASSWORD_RESET_TOKENS_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."PASSWORD_RESET_TOKENS_EMAIL_PK" ON "BALANG"."PASSWORD_RESET_TOKENS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FAILED_JOBS_UUID_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."FAILED_JOBS_UUID_UK" ON "BALANG"."FAILED_JOBS" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PER_AC_TO_TOKE_TY_TOKE_ID_IN
--------------------------------------------------------

  CREATE INDEX "BALANG"."PER_AC_TO_TOKE_TY_TOKE_ID_IN" ON "BALANG"."PERSONAL_ACCESS_TOKENS" ("TOKENABLE_TYPE", "TOKENABLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MIGRATIONS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."MIGRATIONS_ID_PK" ON "BALANG"."MIGRATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSONAL_ACCESS_TOKENS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."PERSONAL_ACCESS_TOKENS_ID_PK" ON "BALANG"."PERSONAL_ACCESS_TOKENS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REPORTS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."REPORTS_ID_PK" ON "BALANG"."REPORTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."USERS_ID_PK" ON "BALANG"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLAIMS_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."CLAIMS_ID_PK" ON "BALANG"."CLAIMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSONA_ACCES_TOKEN_TOKE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."PERSONA_ACCES_TOKEN_TOKE_UK" ON "BALANG"."PERSONAL_ACCESS_TOKENS" ("TOKEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_EMAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BALANG"."USERS_EMAIL_UK" ON "BALANG"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CLAIMS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BALANG"."CLAIMS_ID_TRG" 
            before insert on CLAIMS
            for each row
                begin
            if :new.ID is null then
                select claims_id_seq.nextval into :new.ID from dual;
            end if;
            end;
/
ALTER TRIGGER "BALANG"."CLAIMS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FAILED_JOBS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BALANG"."FAILED_JOBS_ID_TRG" 
            before insert on FAILED_JOBS
            for each row
                begin
            if :new.ID is null then
                select failed_jobs_id_seq.nextval into :new.ID from dual;
            end if;
            end;
/
ALTER TRIGGER "BALANG"."FAILED_JOBS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MIGRATIONS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BALANG"."MIGRATIONS_ID_TRG" 
            before insert on MIGRATIONS
            for each row
                begin
            if :new.ID is null then
                select migrations_id_seq.nextval into :new.ID from dual;
            end if;
            end;
/
ALTER TRIGGER "BALANG"."MIGRATIONS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PERSONAL_ACCESS_TOKENS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BALANG"."PERSONAL_ACCESS_TOKENS_ID_TRG" 
            before insert on PERSONAL_ACCESS_TOKENS
            for each row
                begin
            if :new.ID is null then
                select personal_access_tokens_id_seq.nextval into :new.ID from dual;
            end if;
            end;
/
ALTER TRIGGER "BALANG"."PERSONAL_ACCESS_TOKENS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REPORTS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BALANG"."REPORTS_ID_TRG" 
            before insert on REPORTS
            for each row
                begin
            if :new.ID is null then
                select reports_id_seq.nextval into :new.ID from dual;
            end if;
            end;
/
ALTER TRIGGER "BALANG"."REPORTS_ID_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BALANG"."USERS_ID_TRG" 
            before insert on USERS
            for each row
                begin
            if :new.ID is null then
                select users_id_seq.nextval into :new.ID from dual;
            end if;
            end;
/
ALTER TRIGGER "BALANG"."USERS_ID_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MIGRATIONS
--------------------------------------------------------

  ALTER TABLE "BALANG"."MIGRATIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."MIGRATIONS" MODIFY ("MIGRATION" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."MIGRATIONS" MODIFY ("BATCH" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."MIGRATIONS" ADD CONSTRAINT "MIGRATIONS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLAIMS
--------------------------------------------------------

  ALTER TABLE "BALANG"."CLAIMS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."CLAIMS" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."CLAIMS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."CLAIMS" MODIFY ("PESAN_VALIDASI" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."CLAIMS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."CLAIMS" ADD CHECK ("STATUS" in ('pending', 'accepted', 'rejected')) ENABLE;
  ALTER TABLE "BALANG"."CLAIMS" ADD CONSTRAINT "CLAIMS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASSWORD_RESET_TOKENS
--------------------------------------------------------

  ALTER TABLE "BALANG"."PASSWORD_RESET_TOKENS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."PASSWORD_RESET_TOKENS" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."PASSWORD_RESET_TOKENS" ADD CONSTRAINT "PASSWORD_RESET_TOKENS_EMAIL_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "BALANG"."REPORTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."REPORTS" ADD CONSTRAINT "REPORTS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BALANG"."REPORTS" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FAILED_JOBS
--------------------------------------------------------

  ALTER TABLE "BALANG"."FAILED_JOBS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."FAILED_JOBS" MODIFY ("UUID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."FAILED_JOBS" MODIFY ("CONNECTION" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."FAILED_JOBS" MODIFY ("QUEUE" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."FAILED_JOBS" MODIFY ("PAYLOAD" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."FAILED_JOBS" MODIFY ("EXCEPTION" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."FAILED_JOBS" MODIFY ("FAILED_AT" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."FAILED_JOBS" ADD CONSTRAINT "FAILED_JOBS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BALANG"."FAILED_JOBS" ADD CONSTRAINT "FAILED_JOBS_UUID_UK" UNIQUE ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "BALANG"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."USERS" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."USERS" ADD CONSTRAINT "USERS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BALANG"."USERS" ADD CONSTRAINT "USERS_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONAL_ACCESS_TOKENS
--------------------------------------------------------

  ALTER TABLE "BALANG"."PERSONAL_ACCESS_TOKENS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."PERSONAL_ACCESS_TOKENS" MODIFY ("TOKENABLE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."PERSONAL_ACCESS_TOKENS" MODIFY ("TOKENABLE_ID" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."PERSONAL_ACCESS_TOKENS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."PERSONAL_ACCESS_TOKENS" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "BALANG"."PERSONAL_ACCESS_TOKENS" ADD CONSTRAINT "PERSONAL_ACCESS_TOKENS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BALANG"."PERSONAL_ACCESS_TOKENS" ADD CONSTRAINT "PERSONA_ACCES_TOKEN_TOKE_UK" UNIQUE ("TOKEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLAIMS
--------------------------------------------------------

  ALTER TABLE "BALANG"."CLAIMS" ADD CONSTRAINT "CLAIMS_REPORT_ID_FK" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "BALANG"."REPORTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BALANG"."CLAIMS" ADD CONSTRAINT "CLAIMS_USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "BALANG"."USERS" ("ID") ON DELETE CASCADE ENABLE;
